### ISSUE TITLE
week 01 回饋

### ISSUE THREAD

**Issue by azole** [joeywenchang/git-practice#1]
作業做得很不錯，特別是在實驗觀察的部分，你是少數有為觀察到的內容寫下總結的同學，做得很好。

提醒兩件事:
- 有參考資料的話，記得要列出來。
- 善用圖片輔助。（怎麼在 markdown 與 github 的 markdown 文件中嵌入圖片呢？）

**Comment by joeywenchang** [comment]
1. 參考資料全部來自chatgpt
2. ![圖片描述](./path/to/image.png)

**Comment by azole** [comment]
ok 還是鼓勵讓 chatgpt  搭配 google，全靠 gpt...你還沒有被 gpt 陰過嗎？ ＸＤ

如果沒有其他要討論的，這個 issue 可以關了。

**Comment by joeywenchang** [comment]
主要是Computer Science的東西他很難錯，
4o的品質也比gpt3.5好上不少，3.5真的在唬爛..
目前也會自己判斷跟當初自己學的印象有沒有出入，
在這邊稍微解釋一下～
